### ISSUE TITLE
Characters like" ' " get displayed wrongly in the searchbar after searching

### ISSUE THREAD

**Issue by r2h3** [Lionear/Eveworkbench.Issues#1]
If you search for example for "Overmind 'Hawkmoth' Drone Tuner S10-25T" the characters get replaced by for example " #x27; "

![mangled](https://user-images.githubusercontent.com/15652175/56095228-d1f6ba80-5eda-11e9-9e80-33af8f32fab4.PNG)

**Comment by Lionear** [comment]
Issue has been resolved and wil be released with version 1.4.4
