### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by r2h3** [Lionear/Eveworkbench.Issues#15]
A notification system would be a really nice to have.

Right now a Fitting creator doesnt see if somebody posted a comment in one of his fittings and therefore users asking for more information in the comment section are unlikely to get a response.
The notification system could also, combined with a follow-system of sorts, allow a user to get notified of new fittings made by a user he follows or maybe even a specific tag he's interested in.

**Comment by Lionear** [comment]
This is a good idea but sort of mentioned in Issue/Reqeuest #14 

We will keep this ticket open as we might implement the follow other characters first.

**Comment by Lionear** [comment]
We will release this in version 1.6.3, the notification system will be used when a user follows another user, the user you follow posted a fit or when someone wants to transfer a fit to you.

Release will be early February

**Comment by Lionear** [comment]
Released on Thursday 30th of January.
