### ISSUE TITLE
CPU Calculation faulty

### ISSUE THREAD

**Issue by Koenig-Gaming** [Lionear/Eveworkbench.Issues#18]
I Import my Fitting from Pyfa to EVEWB and i look to the Stats to Confirm.

The Fit have 100% CPU and 100 PG in Pyfa. But on EVEWB it looks over CPU.

Screenshots 
EVEWB Screenshot: https://i.imgur.com/dSVcc2w.png
Pyfa Screenshot: https://i.imgur.com/znjUIrO.png

Hope i can help :)

**Comment by raymondkrahwinkel** [comment]
I looked into this and it looks like you where logged in on EWB and then the calculation is using you're characters skills and in the pyfa screenshot I see that you have selected 'Level 5' and that is probably the cause of the mismatch.

In the mean while we added a drop down where you can also switch between static levels 1 to 5 or you're character skills. And then at level 5 it matches with the pyfa screenshot now :)

![afbeelding](https://user-images.githubusercontent.com/30261334/59504133-893f8b80-8ea2-11e9-8aea-51dea6398efb.png)
