### ISSUE TITLE
Updating a Fittings name doesn't update it on the "New Fittings"section of the Fittings mainpage

### ISSUE THREAD

**Issue by r2h3** [Lionear/Eveworkbench.Issues#2]
If you update a fit by editing it and change the name of it, it will update its name in the fittingpage of the ship, but will not update the name in the "New Fittings" section of the Fittings Mainpage.

Example: Called "Orca, Higgs/Aligned Mining "
https://www.eveworkbench.com/fitting/orca/5b266b16-3407-490e-5fdf-08d6c0180eb5

But keeps its orignial name of "orca, waendrecht"
https://www.eveworkbench.com/fitting

**Comment by Lionear** [comment]
This issue is fixed in the next release
