### ISSUE TITLE
Upvotes are a useful function, downvotes are not

### ISSUE THREAD

**Issue by fonsui** [Lionear/Eveworkbench.Issues#20]
Downvotes do not provide useful function for this tool - an upvote means that someone sees value in the fitting, but a downvote can reduce visibility of a good fitting and is controllable by individuals who lack knowledge and understanding. Example: "I DIED IN YOUR FITTING I AM DOWNVOTING" - this is an emotional response, not a logical one, and cannot be verified in any way. Additionally, personal issues can cause individuals to downvote fittings without any in-game applicability whatsoever. Facebook has "likes" but doesn't have "dislikes", for this reason.

The "scoring" of a fitting should be determined simply by the presence presence or lack of upvotes.

**Comment by Lionear** [comment]
We explicitly chose to use the Reddit style instead of the Facebook style. As a fit can be really terrible the downvote system should be there.
