### ISSUE TITLE
Remove build statistics

### ISSUE THREAD

**Issue by fonsui** [Lionear/Eveworkbench.Issues#21]
Not only is it difficult or impossible to display accurate and complete data for this, considering the inability to calculate for implants, boosters, weather effects, command bursts, and skillpoints, but the primary function of this tool is the management and sharing of fittings; it is not a shipbuilding tool. Shipbuilding takes place in-game for simple builds, and in pyfa for more precise builds; this tool has no facility for shipbuilding, and dev hours spent on this function take away from the primary function of fitting management and sharing.

**Comment by Lionear** [comment]
As its a indicator of what it does with your skills on the characters this function will remain in EWB. If calculations go wrong please report them so we can check it out and fix the issues.

You are right about the part that we are no shipbuilding tool, but the feature was requested by other users and found useful.
