### ISSUE TITLE
Add implants, boosters, and drones to build display

### ISSUE THREAD

**Issue by fonsui** [Lionear/Eveworkbench.Issues#24]
Currently, the only way to display on the page which implants, boosters, and drones should be used is to include them in cargo. These should be displayed as additional rows alongside the High/Mid/Low slots and rigs.

**Comment by Lionear** [comment]
Drones are already shown when they are in the drone bay. We display it just as the EFT is meant to be. 

When the implants are in the current place of the EFT they will be displayed correctly. However, EVE Online lacks the ability to export them as seperate rows at the correct spot so they will be read as normal "cargobay items"

A few updates ago we 'guessed' these kind of items to place them in the correct slots but that gave other issues as some users upload fittings with additional and other High/Mid/Low slot items in the cargobay.

**Comment by Lionear** [comment]
Will be released with version 1.6.0
