### ISSUE TITLE
Allow fitting owners to see counts of up and down votes

### ISSUE THREAD

**Issue by fonsui** [Lionear/Eveworkbench.Issues#26]
Fitting owners should be able to see their individual up and down vote totals on each fitting

**Comment by Lionear** [comment]
We will implement this feature in a future update! Planned to be implemented in version 1.5.1.

**Comment by Lionear** [comment]
Change of plan, will be implemented in version 1.5.2

**Comment by Lionear** [comment]
![image](https://user-images.githubusercontent.com/6653342/58902886-61169680-8704-11e9-9822-a35110ad47d7.png)

In your settings screen you will see the above information
