### ISSUE TITLE
Polarized Weapon Resistances Viewer

### ISSUE THREAD

**Issue by Koenig-Gaming** [Lionear/Eveworkbench.Issues#31]
**Describe the bug**
If you post a fitting with polarized weapons, the resistances looks failure.
Take a look on the Resistances
https://i.imgur.com/eEJrpjA.png

**Comment by Lionear** [comment]
Fitting: https://www.eveworkbench.com/fitting/manticore/a64f0590-9c0a-42d5-d79d-08d6e47469ce

**Comment by raymondkrahwinkel** [comment]
Fixed
