### ISSUE TITLE
Getting 500 Error when trying to publish fit from linked account

### ISSUE THREAD

**Issue by mckernanin** [Lionear/Eveworkbench.Issues#33]
**Describe the bug**
I should be able to publish fits from an alt. I am not.

**To Reproduce**
1. link an alt to your account
2. try to publish a fit
3. no UI feedback provided, 500 error in network tab

**Expected behavior**
I should be able to publish fits from an alt. I am not.

**Screenshots**
![image](https://user-images.githubusercontent.com/6300047/65822123-2f1dc880-e1fc-11e9-808d-7fff930835d4.png)

**Desktop (please complete the following information):**
Windows 10 / Latest firefox

**Additional context**

**Comment by Lionear** [comment]
Thanks for the report, there seems to be a issue indeed.

**Comment by Lionear** [comment]
Issue has been resolved and will be released with version 1.6.0
