### ISSUE TITLE
Publish button returning incorrect response

### ISSUE THREAD

**Issue by mckernanin** [Lionear/Eveworkbench.Issues#37]
**Describe the bug**
When publishing a fit from your profile, you have to click the button twice to see it as public in the dashboard. Then if you check the fit link, it's not published. The API call is returning the old status

**To Reproduce**
1. Go to profile
1. Click on make public
1. See error

**Expected behavior**
On first click the button should turn green for publishing a fit. If you reload after publishing, you'll see it updated with the proper status.

**Screenshots**
![image](https://user-images.githubusercontent.com/6300047/67305749-15963680-f4b3-11e9-9cfb-f64b2bacda46.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 77

**Comment by Lionear** [comment]
Can confirm that this is a bug. We will change this functionality to a dropdown since we introduced a new state next to "Public" and "Private" called "Hidden".

Set to be fixed with the release of EVE Workbench 1.6.1

**Comment by Lionear** [comment]
Can you recheck this? Should be fixed.
