### ISSUE TITLE
Sorting by average price on a user's fittings list is lexicographic instead of ascending/descending

### ISSUE THREAD

**Issue by james-dietz** [Lionear/Eveworkbench.Issues#38]
**Describe the bug**
When sorting the list of a user's fittings by average price (either ascending or descending), the sorting order is lexicographic.

**To Reproduce**
1. Go to [fonsui's eveworkbench user page](https://www.eveworkbench.com/u/fonsui)
2. Click on the Price AVG column header
3. Scroll down to see the list of fittings in the table
4. Observe that the sorting order is improper

**Expected behavior**
Fittings in the table should be sorted by ascending or descending price order as selected by the user when that column is active.

**Screenshots**
https://imgur.com/a/41T3QWC

**Desktop (please complete the following information):**
 - OS: Windows 10 version 2004 (build 19033.1)
 - Browser: Firefox 71 (build 20191202093317)

**Comment by Lionear** [comment]
Can confirm that the behavior on that column is a bit unexpected.

**Comment by Lionear** [comment]
![image](https://user-images.githubusercontent.com/6653342/70460438-9ab2ca80-1ab6-11ea-81cb-71f4ef824044.png)

Fixed, will be released asap.

**Comment by Lionear** [comment]
Fixed
