### ISSUE TITLE
Subscript rather than superscript '3' in 'm3' for 'Cargo' in 'Targeting & Misc' section

### ISSUE THREAD

**Issue by RygelC** [Lionear/Eveworkbench.Issues#41]
In the 'Targeting & Misc' section, for the 'Cargo' field, the '3' in the 'm3' is subscript instead of superscript.

![image](https://user-images.githubusercontent.com/59624511/74280813-2b0ac700-4d15-11ea-9797-df0c4e0b92c7.png)

**Comment by Lionear** [comment]
Will be fixed in version 1.6.4
