### ISSUE TITLE
Display "eve version" as date instead of release name

### ISSUE THREAD

**Issue by Hirmuolio** [Lionear/Eveworkbench.Issues#45]
**Is your feature request related to a problem? Please describe.**
The fit information tells when the fit was submitted by saying the EVE release of that time period. 

For example currently it says 
"EVE Version    Broker Relations"

This is not good way to do it. Eve release names are often insignificant and it is hard to remember when they came out.

**Describe the solution you'd like**

There should be simple date in there with the release name.

**Describe alternatives you've considered**

**Additional context**
Quick quiz: How out long ago "Lifeblood" was.

**Comment by Lionear** [comment]
We have to be honest that this is a struggle that continues and we also had contact with CCP about it what would be the easiest. 

The thing they communicate is the release name, which we also use. When people are adding fits to the website we also show the release date. Perhaps we can show that on the fit page aswel.

**Comment by Lionear** [comment]
What we've done now is that we are using the Name AND the date of release. Think this is the best way for this.
