### ISSUE TITLE
Can't Publish Fittings

### ISSUE THREAD

**Issue by Xiangkunwan** [Lionear/Eveworkbench.Issues#47]
I imported some fittings and I can't seem to publish them.
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to account
2. Click on 'Fits'
3. Then click on 'Import Eve Online fittings'
4. Then click 'Yes'
5. Then wait until a popup says 'Done! Your fits has been imported, please publish them when possible!' and click 'Ok
6. Then click the button that says 'unpublished' 
7. It won't give a choice to publish it

**Expected behaviour**
I expected it to have a drop-down list where I can choose to publish the fits.

**Screenshots**
![2022-03-23 (4)](https://user-images.githubusercontent.com/102434027/161180339-9acc0893-051f-40d9-a3eb-2490a4c31816.png)

**Desktop (please complete the following information):**
 - OS: 22000.593
 - Browser: chrome
 - Version 21H2
![2022-03-31(1)](https://user-images.githubusercontent.com/102434027/161180767-ecc76b7c-984b-4e41-abf8-829f66e71ccf.png)
![2022-03-31 (2)](https://user-images.githubusercontent.com/102434027/161180882-c7d1470b-2e6d-4d43-9b40-61d813c0286f.png)

**Comment by Lionear** [comment]
Thanks for the report. I can confirm that this is a bug  which we will resolve a.s.a.p. For now you can click on the **title** and change the state to **Published** as a work around.

**Comment by Lionear** [comment]
@Xiangkunwan we just released a patch to resolve this issue. Can you please check if you are able to publish fits now through that screen?

**Comment by Xiangkunwan** [comment]
I had all my fits favourited on eve workbench before I deleted them. Now it says "page not found" is there a way to get rid of them? And when I tried to import them again it won't import.

**Comment by Xiangkunwan** [comment]
@Lionear I created some new fit in-game and imported it, and it worked but it only imported the new fits.

**Comment by Lionear** [comment]
> @Lionear I created some new fit in-game and imported it, and it worked but it only imported the new fits.

@Xiangkunwan

This is correct, this is the behaviour we implemented as you deleted the other fits from EVE Workbench. 
We had a lot of occurrences where people removed their imported fits and when they resynced everything was back. If you want to update a fit imported through the ESI just change the fit in EVE and click on the sync button.

Regarding the favourited fits, will have to take a look. As they should be removed automatically if a fit gets removed.

**Comment by Xiangkunwan** [comment]
> Regarding the favourited fits, will have to take a look. As they should be removed automatically if a fit gets removed.

When will this get fixed?

**Comment by Lionear** [comment]
> > Regarding the favourited fits, will have to take a look. As they should be removed automatically if a fit gets removed.
> 
> When will this get fixed?

Dunno, soon I think ;) Its planned for release 1.10.2.

**Comment by Lionear** [comment]
We just pushed the update, fits that are being deleted from now on will also be removed from the favourites. OId data has also been cleaned up.
