### ISSUE TITLE
Unable to upload Laelaps and Raiju fits

### ISSUE THREAD

**Issue by Lionear** [Lionear/Eveworkbench.Issues#49]
Uploading new Tech II hulls gives the error that the EFT could not be validated, see screenshot. Bug was initially submitted by Fonsui on Discord.

![image](https://user-images.githubusercontent.com/6653342/163211845-2f3de1b1-1d6c-41a9-a662-5758b50f849d.png)

Example **Laelaps** fit

`[Laelaps, *Simulated Laelaps Fitting]

Shield Boost Amplifier II

Caldari Navy Heavy Assault Missile Launcher
Caldari Navy Heavy Assault Missile Launcher
Caldari Navy Heavy Assault Missile Launcher
Caldari Navy Heavy Assault Missile Launcher
Caldari Navy Heavy Assault Missile Launcher
Warp Disruption Field Generator II
Improved Cloaking Device II`

Example **Raiju** fit

`[Raiju, *Simulated Raiju Fitting]

Cruise Missile Launcher I
Cruise Missile Launcher I
Cruise Missile Launcher I`

**Comment by raymondkrahwinkel** [comment]
Issue has been fixed, with updating the backend data files for types.
Fits has been tested and confirmed working.
