### ISSUE TITLE
The "Copy to clipboard" button in the list of fits for fleets is copying an old version of the fit

### ISSUE THREAD

**Issue by erstschlag** [Lionear/Eveworkbench.Issues#56]
**Describe the bug**
The "Copy to clipboard" button in the list of fits for fleets is copying an old (probably the initial version) of a fit, not the most current one.

**To Reproduce**
1. Go to https://www.eveworkbench.com/fleets/699f649e-fcfa-424e-5066-08db888abcbb
2. Click on "Copy to clipboard" button
3. Enjoy an old version of the fit

**Expected behavior**
The most recent version of the fit is copied to clipboard.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser based on Chromium 117.0.5938.92

**Comment by raymondkrahwinkel** [comment]
Bug has been fixed, in the given link the EFTs are now matching between fleet and fit details.

**Comment by erstschlag** [comment]
That was blazing fast! Thank you!
