### ISSUE TITLE
Dronerange of all Ships is set 20Km instead of the actual base value + skills/modules

### ISSUE THREAD

**Issue by r2h3** [Lionear/Eveworkbench.Issues#6]
The dronerange value for all ships i have looked at is set to 20km instead of the actual ingame value with skills/modules.
Example: ([worm](https://www.eveworkbench.com/fitting/gila/1fbfd06f-25c4-4cd5-3ff5-08d6c1c240ac))

![drone range](https://user-images.githubusercontent.com/15652175/56210235-ad731d80-6055-11e9-9f69-a14c60948041.PNG)

**Comment by raymondkrahwinkel** [comment]
Issue has been fixed for upcoming release
