### ISSUE TITLE
Sortable Fittings

### ISSUE THREAD

**Issue by r2h3** [Lionear/Eveworkbench.Issues#8]
I personally would find it very useful if you could sort the fittings of for example fitting-searches by Date/Price/Score/Eve-Version maybe even Tags.
As default i would recommend sorting by amount of Score to get a similar effect to reddit posts, where the more interesting posts get pushed to the top. On workbench fittings that are well liked by the userbase would be pushed to the top as result.

By extension it would also make sense to make the authors "upvote" their own fittings by default, to even the playingfield of new fittings' scores. (if that makes sense)

**Comment by fonsui** [comment]
Sort and filter in realtime (as in without a page refresh) are critical missing functions from this tool.

**Comment by Lionear** [comment]
We will add this functionality in 1.5.2.

You will be able to sort on the following things:

- Estimated price
- Date added
- Up/down votes

As the entire search has been changed this will be done realtime.

**Comment by Lionear** [comment]
![image](https://user-images.githubusercontent.com/6653342/58899865-39bccb00-86fe-11e9-8cde-702009e37555.png)
